package com.libraryms.common.error;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    CONFLICT,
    OPTIMISTIC_LOCK_FAILURE,
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    TOO_MANY_ATTEMPTS,
    INTERNAL_SERVER_ERROR
}
